version: '3.4'

services:

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  eventstore:
    image: eventstore/eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - 6113:1113
      - 7113:2113
    volumes:
      - eventstore_data:/var/lib/eventstore

  synapse:
    image: ghcr.io/serverlessworkflow/synapse:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SYNAPSE_API_HOSTNAME=synapse
      - SYNAPSE_PERSISTENCE_WRITEMODEL_DEFAULT_REPOSITORY=EventStore
      - SYNAPSE_PERSISTENCE_READMODEL_DEFAULT_REPOSITORY=MongoDB
      - CONNECTIONSTRINGS__EVENTSTORE=esdb://eventstore:2113?tls=false
      - CONNECTIONSTRINGS__MONGODB=mongodb://mongo:27017
    ports:
      - 42286:42286
      - 41387:41387
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./plugins:/app/plugins
    depends_on:
      - mongo
      - eventstore

volumes:

  mongo_data:
    driver: local

  eventstore_data:
    driver: local

networks:

  default:
    name: synapse