apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-operator
  namespace: synapse
  annotations:
    traffic.sidecar.istio.io/excludeOutboundIPRanges: 10.96.0.1/32
spec:
  selector:
    matchLabels:
      app: synapse-operator
  template:
    metadata:
      labels:
        app: synapse-operator
        version: '0.1.0'
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 10.96.0.1/32
    spec:
      containers:
      - name: synapse-operator
        image: synapse/operator:0.1.0
        imagePullPolicy: IfNotPresent
        env:
          - name: KUBERNETES_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SYNAPSE_CLOUDEVENT_SINK
            value: https://webhook.site/afc2e9c8-8151-437c-a41b-de273251ce57